/*jshint node:true*/
var _fs = require('fs'),
    _path = require('path'),
    _Datauri = require('datauri');
    
var ICON_FOLDER = 'icons';
var ICON_CLASS_PREFIX = 'icon-';
var ICON_EXT = '.scss';
var ICON_DESTINATION = 'app/styles/';
var BANNER = "/**DO NOT MODIFY - THIS FILE WAS AUTO GENERATED BY THE ICON-LIST BLUEPRINT**/";
    
function walkSync(path, callback) {
  _fs.readdirSync(path).forEach(function(name) {
    var filePath = _path.join(path, name);
    var stat = _fs.statSync(filePath);
    if (stat.isFile()) {
      callback(filePath, stat);
    } else if(stat.isDirectory()) {
      walk(filePath, callback);
    }
  });
}

function write(path, data) {
  _fs.writeFileSync(path, data);
}

function getClassForImage(path) {
  var classname = ICON_CLASS_PREFIX + _path.basename(path, _path.extname(path));
  var datauri = new _Datauri();
  
  datauri.encodeSync(path);
  
  return datauri.getCSS({class:classname});
}

function isImage(path) {
  return (/\.(gif|jpg|jpeg|tiff|png|svg)$/i).test(_path.extname(path));
}

module.exports = {
  description:'Generates an icon list',
  
  afterInstall:function(options) {
    var filename = options.args[1];
    var data = BANNER + '\n';
    walkSync(ICON_FOLDER, function(path) {
      if (isImage(path)){
        data += getClassForImage(path) + '\n';
      }
    });
    write(ICON_DESTINATION + filename + ICON_EXT,data);
  }
};
